info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T07:23:32.286Z"}
info: Connected to the database. {"timestamp":"2022-02-11T07:23:35.512Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/book/addbook 
      method - POST 
      IP - ::1
     {"timestamp":"2022-02-11T07:23:51.384Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee2$ (C:\Users\ALANKRITHA\Books\book-store\build\services\user.service.js:104:19)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:32:56.958Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee2$ (C:\Users\ALANKRITHA\Books\book-store\build\services\user.service.js:104:19)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:33:40.085Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:34:50.134Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:35:35.728Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:57:08.802Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:57:10.773Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:57:28.947Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T07:57:31.139Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:04:33.497Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:63:17)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:281:22 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:05:20.104Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T08:07:00.889Z"}
info: Connected to the database. {"timestamp":"2022-02-11T08:07:03.855Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:08:25.212Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:13:04.591Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:15:04.543Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:16:42.293Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:17:06.331Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:17:44.776Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:17:47.294Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:18:06.318Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:20:18.194Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:20:34.950Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:21:07.415Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:23:43.232Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/addbook 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:24:54.480Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T08:30:16.953Z"}
info: Connected to the database. {"timestamp":"2022-02-11T08:30:19.884Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee2$ (C:\Users\ALANKRITHA\Books\book-store\build\services\user.service.js:104:19)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:31:09.864Z"}
error: 
    status - 500 
    message - Error: Invalid user
    at _callee2$ (C:\Users\ALANKRITHA\Books\book-store\build\services\user.service.js:104:19)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-11T08:31:44.732Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T08:36:26.791Z"}
info: Connected to the database. {"timestamp":"2022-02-11T08:36:26.891Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:40:01.966Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:40:32.690Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook?_id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:41:04.650Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:41:20.988Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:42:05.523Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:43:56.130Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:44:38.001Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:44:58.923Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:45:00.443Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/getbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T08:46:00.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T11:42:24.309Z"}
info: Connected to the database. {"timestamp":"2022-02-11T11:42:24.371Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T12:02:10.098Z"}
info: Connected to the database. {"timestamp":"2022-02-11T12:02:10.145Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:04:26.794Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/_id 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:04:42.487Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:04:54.642Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:05:21.061Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:06:04.106Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:06:19.334Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:07:17.513Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:07:30.962Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/addbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:08:42.298Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/addbook 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:08:43.680Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/search/Good%20life 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-11T12:09:30.806Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/search/Good%20life 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:09:44.837Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T12:10:26.546Z"}
info: Connected to the database. {"timestamp":"2022-02-11T12:10:26.588Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:12:36.688Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:13:41.191Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:13:46.204Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T12:15:05.108Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/:id 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:35:43.037Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:35:58.541Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:36:00.380Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:36:05.344Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:36:22.894Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:36:33.195Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:36:34.625Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:40:13.447Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:41:33.333Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:41:51.260Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:42:20.618Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:42:34.247Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:42:50.086Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:44:36.326Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:44:43.159Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/620650a2455c181d9c16eab2 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:45:37.081Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:49:54.663Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:50:34.926Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:51:02.694Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?_id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:52:19.972Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?_id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:52:38.025Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T13:55:53.759Z"}
info: Connected to the database. {"timestamp":"2022-02-11T13:55:53.806Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:56:00.016Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T13:56:29.683Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:02:16.013Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?:id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:02:23.413Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:05:20.440Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:88:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.getBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:103:18)
    at _callee3$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:155:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/getbookbyid?id=62062054d9520c4dec032267 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:05:40.523Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:08:08.954Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:08:09.041Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:11:14.042Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:11:14.095Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:26:15.140Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:26:15.207Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'split')
    at userRole (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:114:29)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:360:14)
    at param (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:371:14)
    at Function.process_params (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:416:3)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:341:12) 
    url - /api/v1/book/updatebookbyid/62062054d9520c4dec032267 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:26:27.166Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:27:56.911Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:27:57.159Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/book/updatebookbyid/62062054d9520c4dec032267 
      method - PUT 
      IP - ::1
     {"timestamp":"2022-02-11T14:27:57.410Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/updatebookbyid/62062054d9520c4dec032267 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:28:24.175Z"}
error: 
    status - 500 
    message - JsonWebTokenError: invalid signature
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:133:19
    at getSecret (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (C:\Users\ALANKRITHA\Books\book-store\node_modules\jsonwebtoken\verify.js:94:10)
    at _callee$ (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:55:45)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userAuth (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:80:17)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3) 
    url - /api/v1/book/updatebookbyid/:id 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:34:13.857Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:35:12.467Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:35:12.519Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/620650a2455c181d9c16eab2 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:35:36.304Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/62062054d9520c4dec032267 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:36:06.167Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/620671196de5b627a034126b 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:36:29.430Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:37:18.470Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:37:18.540Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/620671196de5b627a034126b 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:37:22.408Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/620671196de5b627a034126b 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:37:24.761Z"}
error: 
    status - 500 
    message - ReferenceError: Book is not defined
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:118:13)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.updateBookById (C:\Users\ALANKRITHA\Books\book-store\build\services\BookService.js:135:18)
    at _callee4$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:212:32)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/book/updatebookbyid/620671196de5b627a034126b 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-11T14:37:26.379Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:38:53.388Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:38:53.455Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value " 620671196de5b627a034126b\n" (type string) at path "_id" for model "Book"
    at model.Query.exec (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/book/getbookbyid/%20620671196de5b627a034126b%0A 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:39:48.698Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value " 620671196de5b627a034126b" (type string) at path "_id" for model "Book"
    at model.Query.exec (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/book/getbookbyid/%20620671196de5b627a034126b 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:40:03.964Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:41:41.501Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:41:41.559Z"}
error: 
    status - 500 
    message - CastError: Cast to ObjectId failed for value " 620671196de5b627a034126b" (type string) at path "_id" for model "Book"
    at model.Query.exec (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\ALANKRITHA\Books\book-store\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/book/getbookbyid/%20620671196de5b627a034126b 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-11T14:41:46.321Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'split')
    at userRole (C:\Users\ALANKRITHA\Books\book-store\build\middlewares\auth.middleware.js:114:29)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:360:14)
    at param (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:371:14)
    at Function.process_params (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:416:3)
    at next (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\ALANKRITHA\Books\book-store\node_modules\express\lib\router\index.js:341:12) 
    url - /api/v1/book/deletebookbyid/620671196de5b627a034126b 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-02-11T14:44:22.237Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'title')
    at _callee5$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:268:52)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/book/deletebookbyid/620671196de5b627a034126b 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-02-11T14:45:50.293Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'title')
    at _callee5$ (C:\Users\ALANKRITHA\Books\book-store\build\controllers\BookController.js:268:52)
    at tryCatch (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\ALANKRITHA\Books\book-store\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ALANKRITHA\Books\book-store\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/book/deletebookbyid/620671196de5b627a034126b 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-02-11T14:46:31.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-11T14:47:22.424Z"}
info: Connected to the database. {"timestamp":"2022-02-11T14:47:22.483Z"}
